import { CelestialObjectType } from '@/shared/types/enums'

export const OBJECT_TYPE_LABELS: Record<CelestialObjectType, string> = {
  [CelestialObjectType.Star]: 'Звезда',
  [CelestialObjectType.DoubleStar]: 'Двойная звезда',
  [CelestialObjectType.VariableStar]: 'Переменная звезда',
  [CelestialObjectType.Planet]: 'Планета',
  [CelestialObjectType.Moon]: 'Спутник',
  [CelestialObjectType.Sun]: 'Солнце',
  [CelestialObjectType.Asteroid]: 'Астероид',
  [CelestialObjectType.Comet]: 'Комета',
  [CelestialObjectType.Galaxy]: 'Галактика',
  [CelestialObjectType.Nebula]: 'Туманность',
  [CelestialObjectType.PlanetaryNebula]: 'Планетарная туманность',
  [CelestialObjectType.SupernovaRemnant]: 'Остаток сверхновой',
  [CelestialObjectType.OpenCluster]: 'Рассеянное скопление',
  [CelestialObjectType.GlobularCluster]: 'Шаровое скопление',
}

export const CONSTELLATION_NAMES: Record<string, string> = {
  And: 'Andromeda',    Ant: 'Antlia',         Aps: 'Apus',
  Aqr: 'Aquarius',    Aql: 'Aquila',          Ara: 'Ara',
  Ari: 'Aries',       Aur: 'Auriga',          Boo: 'Boötes',
  Cae: 'Caelum',      Cam: 'Camelopardalis',  Cnc: 'Cancer',
  CVn: 'Canes Venatici', CMa: 'Canis Major',  CMi: 'Canis Minor',
  Cap: 'Capricornus', Car: 'Carina',          Cas: 'Cassiopeia',
  Cen: 'Centaurus',   Cep: 'Cepheus',         Cet: 'Cetus',
  Cha: 'Chamaeleon',  Cir: 'Circinus',        Col: 'Columba',
  Com: 'Coma Berenices', CrA: 'Corona Australis', CrB: 'Corona Borealis',
  Crv: 'Corvus',      Crt: 'Crater',          Cru: 'Crux',
  Cyg: 'Cygnus',      Del: 'Delphinus',       Dor: 'Dorado',
  Dra: 'Draco',       Equ: 'Equuleus',        Eri: 'Eridanus',
  For: 'Fornax',      Gem: 'Gemini',          Gru: 'Grus',
  Her: 'Hercules',    Hor: 'Horologium',      Hya: 'Hydra',
  Hyi: 'Hydrus',      Ind: 'Indus',           Lac: 'Lacerta',
  Leo: 'Leo',         LMi: 'Leo Minor',       Lep: 'Lepus',
  Lib: 'Libra',       Lup: 'Lupus',           Lyn: 'Lynx',
  Lyr: 'Lyra',        Men: 'Mensa',           Mic: 'Microscopium',
  Mon: 'Monoceros',   Mus: 'Musca',           Nor: 'Norma',
  Oct: 'Octans',      Oph: 'Ophiuchus',       Ori: 'Orion',
  Pav: 'Pavo',        Peg: 'Pegasus',         Per: 'Perseus',
  Phe: 'Phoenix',     Pic: 'Pictor',          Psc: 'Pisces',
  PsA: 'Piscis Austrinus', Pup: 'Puppis',    Pyx: 'Pyxis',
  Ret: 'Reticulum',   Sge: 'Sagitta',         Sgr: 'Sagittarius',
  Sco: 'Scorpius',    Scl: 'Sculptor',        Sct: 'Scutum',
  Ser: 'Serpens',     Sex: 'Sextans',         Tau: 'Taurus',
  Tel: 'Telescopium', Tri: 'Triangulum',      TrA: 'Triangulum Australe',
  Tuc: 'Tucana',      UMa: 'Ursa Major',      UMi: 'Ursa Minor',
  Vel: 'Vela',        Vir: 'Virgo',           Vol: 'Volans',
  Vul: 'Vulpecula',
}

export const BORTLE_LABELS: Record<number, string> = {
  1: 'Безупречно тёмное небо',
  2: 'Истинно тёмное небо',
  3: 'Сельское небо',
  4: 'Сельско-пригородный переход',
  5: 'Пригородное небо',
  6: 'Яркое пригородное небо',
  7: 'Пригородно-городской переход',
  8: 'Городское небо',
  9: 'Внутренний город',
}
